[build]
  publish = "dist"
  command = "npm run lint && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22"

[context.production.environment]
  VITE_CONVEX_URL = "https://incredible-lobster-12.eu-west-1.convex.cloud"
