uploads = []
outputs = []

[[generated]]
id = "Wlrr0mBycilG1iVAeJSNZ"
uri = "file://src/assets/games/anagram.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VJhyeM8ns1OceG2LUHDwV"
uri = "file://src/assets/games/attention-archery.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Jrl8ry_gNowVTmlAg3k9f"
uri = "file://src/assets/games/breath-bubbles.png"
type = "image"
title = "Breath Bubbles thumbnail"

[[generated]]
id = "gO9c--hqrUt2AmdMzroF7"
uri = "file://src/assets/games/color-rush.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TalbKWYYAQzEvQDHiBvaK"
uri = "file://src/assets/games/copy-cat.png"
type = "image"
title = "generated_image"

[[generated]]
id = "70U850yfzCYcuRcxpQjO1"
uri = "file://src/assets/games/dual-n-back.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gxzfbhtaGi50_StBNL0IP"
uri = "file://src/assets/games/echo-tap.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1fwm92l7RiahXtfSVfCQH"
uri = "file://src/assets/games/emotion-volcano.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_e2Hjuw3lOVfToYOEXsHM"
uri = "file://src/assets/games/empathy-engine.png"
type = "image"
title = "generated_image"

[[generated]]
id = "qrzgWS336UqnAjGMzGWjo"
uri = "file://src/assets/games/feelings-faces.png"
type = "image"
title = "generated_image"

[[generated]]
id = "iCTgzvybELRHOlXcyXi9S"
uri = "file://src/assets/games/flexibility-frames.png"
type = "image"
title = "Flexibility Frames thumbnail"

[[generated]]
id = "uOxriIYHoH8xaNdUIqY2G"
uri = "file://src/assets/games/box-breathing.png"
type = "image"
title = "Box Breathing thumbnail"

[[generated]]
id = "NnZli6JhJbXHYXkWYf0RB"
uri = "file://src/assets/games/calm-breathing.png"
type = "image"
title = "Calm Breathing thumbnail"

[[generated]]
id = "fr9g4a3l4WyNz-IoismeZ"
uri = "file://src/assets/games/triangle-breathing.png"
type = "image"
title = "Triangle Breathing thumbnail"

[[generated]]
id = "YPyF5z_jRvUF0EIs7RFX0"
uri = "file://src/assets/games/coherent-breathing.png"
type = "image"
title = "Coherent Breathing thumbnail"

[[generated]]
id = "UinY0wXuMrdTEUoGPnGe8"
uri = "file://src/assets/games/grounding.png"
type = "image"
title = "Grounding Garden thumbnail"

[[generated]]
id = "SdgqkZeDvtsGf7iOJQF3P"
uri = "file://src/assets/games/just-right.png"
type = "image"
title = "Just Right thumbnail"

[[generated]]
id = "C_sYu2EKoQOYvHGNdDDQw"
uri = "file://src/assets/games/squish-lab.png"
type = "image"
title = "Squish Lab thumbnail"

[[generated]]
id = "zp3jS4wBcC9VfB_DAf_LN"
uri = "file://src/assets/games/routine-roadmap.png"
type = "image"
title = "Routine Roadmap thumbnail"
