import type { Track } from '@/types';

export const TRACKS: Track[] = [
  {
    id: 'lofi-chill',
    name: 'Chill Lo-Fi',
    emoji: '☕',
    type: 'lofi',
    bpm: 75,
    description: 'Jazzy chords, vinyl crackle, slow beats',
    bestFor: 'Reading, drawing, or winding down after school',
  },
  {
    id: 'lofi-study',
    name: 'Study Beats',
    emoji: '📚',
    type: 'lofi',
    bpm: 85,
    description: 'Uptempo lo-fi for focused study sessions',
    bestFor: 'Homework, revision, or brain games that need concentration',
  },
  {
    id: 'focus-deep',
    name: 'Deep Focus',
    emoji: '🧠',
    type: 'focus',
    description: 'Evolving ambient pads for deep concentration',
    bestFor: 'Long study sessions or tricky puzzles — blocks out distractions',
  },
  {
    id: 'focus-flow',
    name: 'Flow State',
    emoji: '🌊',
    type: 'focus',
    description: 'Gentle tones to maintain flow state',
    bestFor: 'Creative work, writing, or getting "in the zone" for games',
  },
  {
    id: 'nature-rain',
    name: 'Gentle Rain',
    emoji: '🌧️',
    type: 'nature',
    description: 'Soft filtered noise like distant rainfall',
    bestFor: 'Falling asleep, calming anxiety, or relaxing after a busy day',
  },
  {
    id: 'nature-wind',
    name: 'Forest Wind',
    emoji: '🌲',
    type: 'nature',
    description: 'Breezy ambient sounds through trees',
    bestFor: 'Reducing stress, calming down, or meditation breaks',
  },
  {
    id: 'meditation-breath',
    name: 'Breathing Guide',
    emoji: '🧘',
    type: 'meditation',
    description: 'Tonal breathing guide — inhale 4s, exhale 4s',
    bestFor: 'Panic moments, before a test, or when you feel overwhelmed',
  },
  {
    id: 'meditation-calm',
    name: 'Calm Mind',
    emoji: '☮️',
    type: 'meditation',
    description: 'Slow oscillating tones for mindfulness',
    bestFor: 'Before bed, after an argument, or when your brain feels too busy',
  },
];
