// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/noodle-quest/GameCards.tsx": () => import("../components/mockups/noodle-quest/GameCards.tsx"),
  "./components/mockups/noodle-quest/GameHub.tsx": () => import("../components/mockups/noodle-quest/GameHub.tsx"),
  "./components/mockups/noodle-quest/PlayScreen.tsx": () => import("../components/mockups/noodle-quest/PlayScreen.tsx")
};
